package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Premium Light Theme Palette
val md_theme_light_primary = Color(0xFF4F46E5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF312E81)
val md_theme_light_secondary = Color(0xFF0284C7)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0F2FE)
val md_theme_light_onSecondaryContainer = Color(0xFF075985)
val md_theme_light_tertiary = Color(0xFF059669)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD1FAE5)
val md_theme_light_onTertiaryContainer = Color(0xFF065F46)
val md_theme_light_background = Color(0xFFF8FAFC)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFF1F5F9)
val md_theme_light_onSurfaceVariant = Color(0xFF475569)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFFCBD5E1)

// Premium Deep OLED Dark Theme Palette
val md_theme_dark_primary = Color(0xFF818CF8)
val md_theme_dark_onPrimary = Color(0xFF1E1B4B)
val md_theme_dark_primaryContainer = Color(0xFF3730A3)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_secondary = Color(0xFF38BDF8)
val md_theme_dark_onSecondary = Color(0xFF0C4A6E)
val md_theme_dark_secondaryContainer = Color(0xFF0369A1)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0F2FE)
val md_theme_dark_tertiary = Color(0xFF34D399)
val md_theme_dark_onTertiary = Color(0xFF064E3B)
val md_theme_dark_tertiaryContainer = Color(0xFF047857)
val md_theme_dark_onTertiaryContainer = Color(0xFFD1FAE5)
val md_theme_dark_background = Color(0xFF0B0F19)
val md_theme_dark_onBackground = Color(0xFFF1F5F9)
val md_theme_dark_surface = Color(0xFF161E2E)
val md_theme_dark_onSurface = Color(0xFFF1F5F9)
val md_theme_dark_surfaceVariant = Color(0xFF212D42)
val md_theme_dark_onSurfaceVariant = Color(0xFF94A3B8)
val md_theme_dark_error = Color(0xFFA8F2FA)
val md_theme_dark_onError = Color(0xFF7F1D1D)
val md_theme_dark_outline = Color(0xFF334155)
